### PR TITLE
docker run -it fails if there is not a TTY

### PR DESCRIPTION
**Pull request by jbeal-work**

### CODE REVIEW

**Comment by korydraughn** [comment]
I've confirmed that this change works. However, it disables color in the output. Having color helps to identify problems with the build faster.

A better approach is to make removal of `-it` optional. Hence, the following:
```bash
USAGE: build_jar.sh [OPTIONS]

Options:
   -i, --non-interactive        Launches docker container without -i and -t.
```
Then you can run `build_jar.sh --non-interactive` and get the expected results.

We can work on the short option. I'm not crazy about using `-i` as the short option. It conflicts with enabling interactive mode for other commands (i.e. `docker run`).

**Comment by trel** [comment]
Agreed.

How about `-n`?    Is that less bad?   Or good, even?

**Comment by korydraughn** [comment]
`-n` could work. I'll keep looking around too. If there's an option that doesn't have a common meaning in Linux, then we can use that. We just have to find it.

**Comment by jbeal-work** [comment]
Once people know what option you want I am happy to code it or to close this pull which is really a demonstration.

**Comment by korydraughn** [comment]
These are the only resources I could find regarding standard CLI options.
- https://tldp.org/LDP/abs/html/standard-options.html
- http://www.catb.org/~esr/writings/taoup/html/ch10s05.html
- https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html
- https://www.gnu.org/prep/standards/html_node/Option-Table.html#Option-Table

And based on what I've read, we should use a letter that has no established meaning or force users to pass the long option name.

@jbeal-work Let's go with just providing the long option name. The long name is clear and forces the user to be explicit about what they want.
```bash
USAGE: build_jar.sh [OPTIONS]

Options:
  --non-interactive    Launches docker container without -i and -t.
```
This will require that we add a `-h` and `--help` option and update the README too. I'm happy to let you implement this. Or if you rather I do it, that is fine as well.

**Comment by korydraughn** [comment]
Superseded by #173

**Pull request closed without merging**
