### PR TITLE
[#162] Updated README

### PR DESCRIPTION
**Pull request by korydraughn**
for next release.

release version number suggestions:
- 2.1.0
  - at the moment, i think this is the most appropriate version
  - this signals, "Hey, we changed some things, but you're safe to upgrade. Consider looking over the README."
- 3.0.0
  - this feels like overkill
  - for the most part, only the internals of the app have changed

we need to consider what things constitute a breaking change in regards to NFSRODS
  - shutdown handling is slightly different (use ctrl-c)
  - building is a two-step process now (docker image no longer builds jar)
  - docker run does not require `-i`

### CODE REVIEW

**Comment by trel** [comment]
Agreed, 2.1.0 feels most correct.

Do we know, at this time, what would ever make us release 3.0.0?   Looking over the issues list... there might be one candidate... but mostly they look like fixes/tweaks to the existing interface/approach.

**Comment by korydraughn** [comment]
I don't think any of the existing issues would require a bump to 3.0.0. That's just at a glance though.

**Comment by michael-conway** [comment]
Hey guys I'd suggest to consider aligning the version numbers with the iRODS version number? There's a lot of history here! One reason that the Jargon version numbers had (and this went a looooong time back) 4 segments was to be able to release a Jargon version as a companion to the iRODS release X.X.X leaving an additional sub-minor version to allow patches within the scope of an iRODS release. That may be something that gets dropped soon in Jargon as it never was quite that neat, but it does seem helpful to know at a glance what version of NFSRods goes with the iRODS release. It is quite common that each iRODS release requires changes in the client code! Thus I'd suggest making NFSRods 4.2 or 4.3 as the iRODS server advances?

**Comment by korydraughn** [comment]
We've spent some time discussing the idea and have decided on 2.1.0.

The primary reasoning being:
- Because NFSRODS is a client, it doesn't feel correct to tie it to a specific version of the iRODS server.
- Using that versioning scheme means we'd have to release a new version of NFSRODS with every release of the iRODS server, even when NFSRODS is unchanged.

Aligning the version number better fits libraries and plugins given they have to maintain backwards compatibility and deal with differences between servers.

**Pull request merged**
