### PR TITLE
[#35] Added negotiation_policy option to server config

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
Looks nice.   The default appears to be `CS_NEG_REFUSE`, which is what we want.

Is it required that `negotiation_policy` be defined in the `server.json`?

**Comment by michael-conway** [comment]
Seems better to have it deploy time configurable if that's the question...

**Comment by trel** [comment]
I think we should make it required to be defined in `server.json` - same as the other things?

**Comment by korydraughn** [comment]
it is not required to be defined.  it will always default to REFUSE.

**Comment by korydraughn** [comment]
All configuration options are now required.

**Pull request merged**
