### PR TITLE
Fix typo: 'exisiting' changed to 'existing'

### PR DESCRIPTION
**Pull request by ganning127**

### CODE REVIEW

**Comment by trel** [comment]
please # it.

**Comment by ganning127** [comment]
done!

**Comment by korydraughn** [comment]
Very weird.

**Comment by korydraughn** [comment]
Perhaps a bug in github?

**Comment by ganning127** [comment]
Hmmm, that's really weird: https://stackoverflow.com/questions/74523590/what-constitutes-a-branch-with-too-many-changes-for-github-pr-rebase-merging

**Comment by trel** [comment]
from one of those answers... "This is almost certainly a timeout-based situation"

so... feels like the GitHub backend is backed-up and taking too long... so, we let it ride... maybe it will resolve.

code is small and looks good - no action at this time to wait.

**Review by korydraughn — APPROVED** [review]
Should we try opening a new PR with the same changes to see what happens?

**Comment by korydraughn** [comment]
@ganning127 Please open a new PR with the same changes.

**Comment by ganning127** [comment]
Since this PR originally couldn't be merged (GitHub error message: "This branch cannot be rebased due to too many changes"), we created a new PR (#185) and that was merged instead. Closing this PR.

**Pull request closed without merging**
