### PR TITLE
[#109] Added option that disables stats during the list operation.

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
Did you confirm/see that objects may 'leak' through without the stat?   That iRODS won't already have taken care of that before sending to NFSRODS?

**Comment by korydraughn** [comment]
I haven't tested this yet.

**Comment by korydraughn** [comment]
#51 is the reason why the stat is there. Do we still want to move forward with this PR?

**Comment by trel** [comment]
This is a performance gain at the price of incorrectness.

I don't see how we justify removing the stat - unless we can carefully/correctly spell out when someone would not get incorrect listings due to the use case in #51.

**Comment by korydraughn** [comment]
Jargon uses GenQuery to fetch the entries within a collection. GenQuery will filter the listing based on whether the user is a rodsadmin. With that, it should be safe to remove this stat entirely. rodsadmins will be able to *see* all objects. non-rodsadmins will only be able to see things shared with them.

Should we remove the stat instead of adding an option to disable it?

**Comment by korydraughn** [comment]
The only reason to keep the stat is if a rodsadmin wants to avoid seeing inaccessible objects.

**Comment by trel** [comment]
Okay, so only admins will see possibly inaccessible data objects.  I think that's a strong enough case to remove the `stat()` and not worry about an extra config.  Perhaps we keep the config in a branch, in case this comes up later?

**Comment by korydraughn** [comment]
We could also invert the option (i.e. `hide_inaccessible_entries_on_list_operation`) and have it default to false. If no one complains about inaccessible entries in say a year, we remove it entirely.

**Comment by trel** [comment]
Let's keep it in reserve rather than adding configs to remove later?

**Comment by korydraughn** [comment]
Ok. I don't think we need to keep this code in a branch or anything. It's extremely easy to reproduce.

I'll go ahead and update this PR to remove the stat.

**Pull request closed without merging**
